[package]
name = "eax"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eax = "0.4.1"
aes = "0.7.5"
rand = "0.8.4"