[package]
name = "mersenne_twister"
version = "0.1.0"
authors = ["glancydev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_mt = "4.0.1"
