[package]
name = "chacha20poly1305"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.9.0"
rand = "0.8.4"
rand_core = "0.6.3"
