[package]
name = "sm2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsm = {path = "libsm"}
num-bigint = "0.2"
byteorder = "1.4.3"
to_vec = "0.1.0"
