[package]
name = "fish_3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threefish = "0.4.0"
rand = "0.8.4"
rand_core = "0.6.3"
cipher = "0.3"
