[package]
name = "fish_2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twofish = "0.6.0"
rand = "0.8.4"
rand_core = "0.6.3"
