[package]
name = "salvum_passwd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
passwords = "3.1.7"

[dependencies.passwords]
version = "3.1.7"
features = ["hasher"]