[package]
name = "salvum_aes"
version = "0.1.0"
authors = ["security@qvlx.ai <security@qvlx.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.0"
structview = "1.1.0"