[package]
name = "cast5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cast5 = "0.10.0"
rand_core = "0.6.3"
hex = "0.4.3"
rand = "0.8.4"
